package c4lab.iot.smarthomevisualeditor.design;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.FormLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextField;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { ¡K }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class ComponentEditorPageDesign extends FormLayout {
	protected Label lblName;
	protected TextField inputName;

	public ComponentEditorPageDesign() {
		Design.read(this);
	}
}
