package c4lab.iot.smarthomevisualeditor.design;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;
import fi.jasoft.dragdroplayouts.DDGridLayout;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { ¡K }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class TargetDisplayDesign extends VerticalLayout {
	protected DDGridLayout target;

	public TargetDisplayDesign() {
		Design.read(this);
	}
}
